---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-gpu-plugin
  namespace: kube-system
spec:
  interval: 1h
  maxHistory: 3
  dependsOn:
  - name: node-feature-discovery
    namespace: kube-system

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  values:
    controllers:
      main:
        type: daemonset
        strategy: RollingUpdate
        
        containers:
          main:
            image:
              repository: docker.io/intel/intel-gpu-plugin
              tag: 0.34.1@sha256:3fae94bca1022ca558a1f6768c34760f38f80a2e64f8a72216f10e98746c8124
              pullPolicy: IfNotPresent
            
            args:
              - -shared-dev-num
              - "3"
            
            # TODO(intel-gpu-plugin): Add probes
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            
            resources:
              requests:
                cpu: 15m
                memory: 64M
              limits:
                memory: 64M

    service:
      main:
        controller: main
        enabled: false

    persistence:
      devfs:
        type: hostPath
        hostPath: /dev/dri
        hostPathType: Directory
        globalMounts:
          - path: /dev/dri
            readOnly: true
      sysfs:
        type: hostPath
        hostPath: /sys/class/drm
        hostPathType: Directory
        globalMounts:
          - path: /sys/class/drm
            readOnly: true
      kubeletsockets:
        type: hostPath
        hostPath: /var/lib/kubelet/device-plugins
        hostPathType: Directory
        globalMounts:
          - path: /var/lib/kubelet/device-plugins

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: intel.feature.node.kubernetes.io/igpu
              operator: In
              values:
              - "true"
          - matchExpressions:
            - key: intel.feature.node.kubernetes.io/arc
              operator: In
              values:
              - "true"
